/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ag.clinic.reception;

import com.ag.clinic.DB.DB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahmed basuny
 */
public class NewVisitFull extends javax.swing.JFrame {

    /**
     * Creates new form NewVisitFull
     */
    
    private DefaultTableModel model;
    static int i;
    static int new_visit;
    
    public NewVisitFull() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIDsearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNameSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnVisit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("زيارة جديدة");

        txtIDsearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("ID");

        txtNameSearch.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setText("الأسم");

        jButton1.setText("بحث");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "الأسم ", "عدد الزيارات ", "تاريخ اخر زيارة"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        btnVisit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVisit.setText("زيارة جديدة");
        btnVisit.setEnabled(false);
        btnVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIDsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVisit)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(146, 146, 146))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnVisit)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(txtIDsearch.getText().trim().equals("") && txtNameSearch.getText().trim().equals("")){
        JOptionPane.showMessageDialog(rootPane, "من فضلك أدخل طريقة البحث  ");
        }else if(!txtIDsearch.getText().trim().equals("") && !txtNameSearch.getText().trim().equals("")){
        JOptionPane.showMessageDialog(rootPane, "من فضلك أدخل طريقة بحث واحدة ");
        }else if(txtNameSearch.getText().trim().equals("") && !txtIDsearch.getText().trim().equals("")){        //search with ID
        
            try{
            Connection con = new DB().getMySqlConn();
            Statement stmt = con.createStatement();
            ResultSet rs;
            String sqlRet = "select p.patient_id, p.patient_name ,v.visit_number ,v.visit_date from patient p join patient_visit v on p.patient_id=v.patient_id where p.patient_id like'%"+txtIDsearch.getText()+"%'";
            
            rs = stmt.executeQuery(sqlRet);
            if(rs.next()){
     //           System.out.println("true....");
                int id      = rs.getInt(1);
                String name = rs.getString(2);
                int no_visit= rs.getInt(3);
                String date = rs.getString(4);
                
                if(table.getRowCount() != 0){
                
                int row = table.getRowCount();                     //  make table empty     
                model.setRowCount(0);
                model.fireTableRowsDeleted(0, 0);
                
                }
      
                model = (DefaultTableModel) table.getModel();
                model.insertRow(table.getRowCount(), new Object[]{id,name,no_visit,date});
                
            }else{
            JOptionPane.showMessageDialog(rootPane, "لم يتم العثور على نتائج لبحثك ");
            }
            
            con.close();
            }catch(SQLException x){
            x.printStackTrace();
            }
        }else if(txtIDsearch.getText().trim().equals("") && !txtNameSearch.getText().trim().equals("")){
        
            try{
            Connection con = new DB().getMySqlConn();
            Statement stmt = con.createStatement();
            ResultSet rs;
            
            String sqlsearchName = "select p.patient_id, p.patient_name ,v.visit_number ,v.visit_date from patient p join patient_visit v on p.patient_id=v.patient_id where p.patient_name like'%"+txtNameSearch.getText()+"%'";
            rs = stmt.executeQuery(sqlsearchName);
            if(rs.next()){
          //      System.out.println("doneeee..");
                int id      = rs.getInt(1);
                String name = rs.getString(2);
                int no_visit= rs.getInt(3);
                String date = rs.getString(4);
                
                if(table.getRowCount() != 0){
                
                int row = table.getRowCount();                     //  make table empty     
                model.setRowCount(0);
                model.fireTableRowsDeleted(0, 0);
                
                }
      
                model = (DefaultTableModel) table.getModel();
                model.insertRow(table.getRowCount(), new Object[]{id,name,no_visit,date});
                
            }else{
            JOptionPane.showMessageDialog(rootPane, "لم يتم العثور على نتائج لبحثك ");
            }
                
            con.close();
            }catch(SQLException exe){
            exe.printStackTrace();
            }
            
        }
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
         btnVisit.setEnabled(true);
        
        i =  (int) table.getValueAt(table.getSelectedRow(), 0);
        int no_visit = (int) table.getValueAt(table.getSelectedRow(), 2);
        new_visit = no_visit+1;
    }//GEN-LAST:event_tableMouseClicked

    private void btnVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitActionPerformed
        // TODO add your handling code here:
        try{
        Connection con = new DB().getMySqlConn();
        Statement stmt = con.createStatement();
        ResultSet rs;
        
         DateFormat dateFormat = new SimpleDateFormat(" yyyy/MM/dd");       //current date 
    Date date = new Date();
    String currentDate = dateFormat.format(date);
        
        String sqlNewVisit = "update patient_visit set visit_number="+new_visit+",visit_date='"+currentDate+"' where patient_id ="+i;
        stmt.executeUpdate(sqlNewVisit);
        
        JOptionPane.showMessageDialog(rootPane, "تم إدخال الزيارة الجديدة");
        
        btnVisit.setEnabled(false);
         int row = table.getRowCount();                     //  make table empty     
         model.setRowCount(0);
         model.fireTableRowsDeleted(0, 0);
        con.close();
        }catch(SQLException ex){
        ex.printStackTrace();
        }
    }//GEN-LAST:event_btnVisitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewVisitFull.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewVisitFull.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewVisitFull.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewVisitFull.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewVisitFull().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVisit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtIDsearch;
    private javax.swing.JTextField txtNameSearch;
    // End of variables declaration//GEN-END:variables
}
